api:
  prefix: /api/v1
server:
  port: 8080

spring:
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3308/osahan-eat
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    client:
      dns:
        lookup: use_dns_cache
    bootstrap-servers: localhost:2181
    producer:
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 610381338-pfebbbo2s644acrpigs5no1aeejqhmm9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: "{base-url}/login/oauth2/code/google"
          facebook:
            client-id: YOUR_FACEBOOK_CLIENT_ID
            client-secret: YOUR_FACEBOOK_CLIENT_SECRET
            scope:
              - public_profile
              - email
            redirect-uri: "{base-url}/login/oauth2/code/facebook"

app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 10800000
  jwt-expiration-refresh-token: 14400000

logging:
  level:
    org.springframework.security: DEBUG

upload:
  path: uploads/
  max-file-size: 10485760


redis:
  host: localhost
  port: 6380
